spring:
  jpa:
    database: MYSQL
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      region:
        static: ${AWS_S3_REGION}
      s3:
        bucket: ${AWS_S3_BUCKET_NAME}
      stack:
        auto: false

server:
  servlet:
    context-path: /api

jwt:
  secret: ${JWT_SECRET_KEY}

api-key:
  gpt-trip: ${GPT_API_KEY}
  amadeus:
    accessKey: ${AMADEUS_ACCESS_KEY}
    secretKey: ${AMADEUS_SECRET_KEY}
  open-weather: ${OPEN_WEATHER_API_KEY}