spring:
  jpa:
    database: MYSQL
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.38.54.32:3306/trip
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

jwt:
  secret : ${JWT_SECRET_KEY}

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}
    region:
      static: ${AWS_S3_REGION}
    stack:
      auto: false

api-key:
  chat-gpt: ${GPT_API_KEY}